services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppZap\Migrator\Command\MigrateCommand:
        tags:
            - name: 'console.command'
              command: 'migration:migrateall'
              schedulable: false
