services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Portrino\PxDbmigrator\:
      resource: '../Classes/*'
      exclude: '../Classes/Domain/Model/*'

    Portrino\PxDbmigrator\Command\MigrateCommand:
        tags:
            - name: 'console.command'
              command: 'migration:migrateall'
              description: 'Executes pending *.sh, *.sql and *.typo3cms migration files from the configured migrations directory.'
              schedulable: false
